### ISSUE TITLE
Error in the mm.sh script?

### ISSUE THREAD

**Issue by vnijhuis** [uvoteam/mysql-monitoring#1]
Hello,

Great job here, i only have one problem. See below. 

Error in Zabbix items screen:
`Received value [/etc/zabbix/mm.sh: line 2: syntax error near unexpected token `('/etc/zabbix/mm.sh: line 2: `hostname=$(hostname -f) get_mysqld_sockets() {'] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]`

when trying to run the script by hand in the command line i get:

```
/etc/zabbix/mm.sh: line 2: syntax error near unexpected token `('
/etc/zabbix/mm.sh: line 2: `hostname=$(hostname -f) get_mysqld_sockets() {'
```

What am i doing wrong here. My setup:

```
mysql  Ver 14.14 Distrib 5.6.33
Zabbix 3.2
```

Best regards,
Vincent Nijhuis

**Comment by firaxis** [comment]
Hello,

Thanks.

Could you please say what linux distribution do you use ?
It looks like the issue with bash.
And also, please try running

```
/usr/bin/env bash -x /etc/zabbix/mm.sh
```

**Comment by vnijhuis** [comment]
Hello, 

I use CentOS 7. When i try your command i see the following output.

```
/usr/bin/env bash -x /etc/zabbix/mm.sh
/etc/zabbix/mm.sh: line 2: syntax error near unexpected token `('
/etc/zabbix/mm.sh: line 2: `hostname=$(hostname -f) get_mysqld_sockets() {'
```

I think it may be due to Windows encoding? I'll check that.

**Comment by vnijhuis** [comment]
Small steps. 

It was indeed encoding.  Now the following problem.

```
/usr/bin/env bash -x /etc/zabbix/mm.sh
++ hostname
+ hostname="hostname"
+ parse_args
+ case "$1" in
+ echo '/etc/zabbix/mm.sh: error - unrecognized option ""'
/etc/zabbix/mm.sh: error - unrecognized option ""
+ exit 1
```

**Comment by firaxis** [comment]
Right,

You need to run this script with options, like specified in https://github.com/firaxis/mysql-monitoring/blob/master/mm.conf

I will update this default output shortly.

**Comment by vnijhuis** [comment]
This is what Zabbix Items screens gives me at this moment. 

I fixed the problem before. 

```
Received value [sh: /etc/zabbix/mm.sh: Permission denied] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
```

**Comment by firaxis** [comment]
Please, check permissions for /etc/zabbix/mm.sh
It must be 755, if not, run

```
chmod +x /etc/zabbix/mm.sh
```

**Comment by vnijhuis** [comment]
The permissions are fine. 
Maybe due to mysql version diverrences?
mysql  Ver 14.14 Distrib 5.6.33

-rwxr-xr-x    1 root   root    4057 Sep 16 11:14 mm.sh

I tright the following command by hand:

```
mysqladmin --defaults-extra-file=/etc/zabbix/.my.cnf -S localhost ping
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket 'localhost' (2)'
Check that mysqld is running and that the socket: 'localhost' exists!
```

this looks wrong to me.

mysqld is running

**Comment by firaxis** [comment]
That's because lack of testing..
I need some time to look into this issue.

**Comment by vnijhuis** [comment]
I also changed that command now. 
mysqladmin --defaults-extra-file=/etc/zabbix/.my.cnf ping  

that works

Zabbix items screen now tells me:

```
Received value [rm: cannot remove ‘/tmp/mm.alive_instances.dat’: Operation not permittedmv: cannot move ‘/tmp/mm.alive_instances.dat~’ to ‘/tmp/mm.alive_instances.dat’: Operation not permitted/etc/zabbix/mm.sh: line 15: /tmp/mm.zabbix_sender.log: Permission denied] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
```

so now i have a permission problem server side the zabbix user is already persistent in de sudoers.

**Comment by firaxis** [comment]
Regarding

> mysqladmin --defaults-extra-file=/etc/zabbix/.my.cnf -S localhost ping

It's quite wrong command, there must be specified path to socket.
Show me please output of following command

```
ps uax| grep mysql
```

Regarding

> Received value [rm: cannot remove ‘/tmp/mm.alive_instances.dat’: Operation not permittedmv: cannot move ‘/tmp/mm.alive_instances.dat~’ to ‘/tmp/mm.alive_instances.dat’: Operation not permitted/etc/zabbix/mm.sh: line 15: /tmp/mm.zabbix_sender.log: Permission denied] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

Try chown /tmp/mm.\* and to user zabbix or just remove this files, permissions seems to be broken after script was runned by root user

**Comment by vnijhuis** [comment]
My problem existed within the zabbix account. 

Now i only have one problem left :+1:  

Template App Mysql Monitoring: Get slaves status: mm.replication_status

```
Received value [ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 1ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 1ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 1ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 10] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
```

No changes made except for [this change](https://github.com/firaxis/mysql-monitoring/issues/1#issuecomment-247563596)

**Comment by firaxis** [comment]
> Received value [ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 1ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 1ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 1ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all slaves status' at line 10] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

It's because Multi-Source Replication is not supported in your version of mysqld.
I will try to do a workaround.

**Comment by vnijhuis** [comment]
Hello, 

Your last comment was gold. i upgraded successfully to 5.7.15. Now it works. 

So i had to change a few things. but i am there now. 

I also had to change de mv command for the mm.\* files to cp because they could not be created in some way.

Thank you for your help. keep up the good work.

Best regards, 
Vincent Nijhuis
